packages:
  - create-gloom

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@prisma/engines'
  - esbuild
  - msw
  - prisma

overrides:
  '@hono/node-server@<1.19.13': '>=1.19.13'
